import {
// sbudnicN,
mia,
eliot,
sbudnicNW,
theo,
rick,
dheraj,
ashton,
daniel,
haley,
marco,
filip,
maddie,
benji,
selia,
lia,
jenn,
gabby,
rap,
lorenzo,
kazen,
} from "../content/images"

const team = [
{
id: 2,
title: "Marco Cross",
subtitle:
"Hardware isn't hard. Perpetually inventing, designing, and making. I get antsy if my hands stop moving.",
category: "Subsystem Managing Engineer, Chief Engineer",
image: marco,
team: "AOCS",
position: "Subsystem Managing Engineer",
},
{
id: 3,
title: "Dheraj Ganjikunta",
subtitle:
"Let's go to space! What inspires me to work on SBUDNIC is the promise of 'space for everyone,' which is why I'm committed to developing the program as an open source project in record time. I'm part of Brown's class of 2022, and am studying Economics and International & Public Affairs. I'll be at McKinsey & Co in NYC after graduation. In my free time, I enjoy hiking and reading sci-fi (The Culture and The Expansre are my favorite series!)",
category: "Program Manager",
position: "Lead Program Manager",
image: dheraj,
team: "Program Management and Public Relations",
},
{
id: 28,
title: "Selia Jindal",
subtitle:
"",
team: "Program Management and Public Relations",
category: "General",
position: "Project Director",
image: selia,
},
{
id: 90,
title: "Miku Suga",
subtitle:
"",
category: "",
position: "Public Relations Analyst",
team: "Program Management and Public Relations",
image: "https://cs.brown.edu/courses/csci1430/2022_Spring/staff_images/portrait/msuga.jpg",
},
{
id: 6,
title: "Ashton Lam",
subtitle: "",
category: "Public Relations Analyst",
position: "Public Relations Analyst",
image: ashton,
team: "alumni",
},
{
id: 21,
title: "Elizabeth Kimmel",
subtitle:
"",
team: "alumni",
category: "alumni",
position: "Engineer",
image: sbudnicNW,
},
{
id: 22,
title: "Cameron Goodreau",
subtitle:
"",
team: "Testing",
category: "",
position: "Subsystem Managing Engineer",
image: "https://media.licdn.com/dms/image/v2/D4E03AQH-kzxR21B34Q/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1695787186776?e=2147483647&v=beta&t=ZH5Wnn_UXhiCONinYYIB3QbSVx52arzQDfai5bZBOgc",
},
{
id: 7,
title: "Maddie Simon",
subtitle:
"I'm a member of the Brown class of '24 studying Biomedical Engineering! I'm super excited to be helping out with this project and have already learned so much.",
category: "Testing Team Member",
position: "Engineer",
image: maddie,
team: "Testing",
},
{
id: 45,
title: "Benjamin Kilimnik",
subtitle:
"A junior at Brown University studying computer science with a focus on systems research, data science, and web design. When I'm not coding up a hot mess in the Computer Science department, you can find me working at the Center for Computation and Visualization, researching for Systems@Brown or reading historical fiction next to a radiator.",
team: "alumni",
category: "",
position: "Public Relations and Engineer (Thermal Control System)",
image: benji,
},
{
id: 9,
title: "Daniel Wang",
subtitle:
"Daniel is a rising senior MechE, fascinated by the neat applications of classical mechanics, who enjoys thinking about challenging energy distribution and efficiency problems. More broadly, Daniel wants to get more people thinking about civilization's major mass+energy flows, such as animal agriculture, and how they can be radically reimagined or replaced altogether.",
category: "alumni",
image: daniel,
},
{
id: 11,
title: "Duncan Crane",
subtitle:
"",
team: "TTC + GSEG",
category: "Telemetry, Tracking, Control",
position: "Subsystem Managing Engineer",
image: "https://scontent-bos5-1.xx.fbcdn.net/v/t1.6435-1/32947065_549485482111747_8112015056780132352_n.jpg?stp=dst-jpg_s480x480&_nc_cat=100&ccb=1-7&_nc_sid=e4545e&_nc_ohc=KxZnyIFZ4rwQ7kNvgHpcKqt&_nc_ht=scontent-bos5-1.xx&_nc_gid=AD-yAzi-kub-U_ux1DSn6sh&oh=00_AYAZGL7gdA1vd3nz2T5IUFSt-UcQqNJ5itmo6aSrribksg&oe=67194220",
},
{
id: 10,
title: "Theo Fernandez",
subtitle:
"First year from Los Angeles, California who plans on concentrating Computer Science. I love computers, engineering, and space, as well as surfing, watching movies, biking, and tinkering.",
team: "TTC + GSEG",
category: "Telemetry, Tracking, Control",
position: "Engineer",
image: theo,
},
{
id: 12,
title: "Anthony Bishop-Gylys",
subtitle:
"",
team: "TTC + GSEG",
category: "Telemetry, Tracking, Control",
position: "Subsystem Managing Engineer",
image: "https://fanchaolab.com/assets/images/1667186486781-192x192.jpg",
},
{
id: 14,
title: "Lia Lubit",
subtitle:
"",
team: "THERM",
category: "",
position: "Thermal Control System Engineer",
image: lia,
},
{
id: 13,
title: "Eliot Laidlaw",
subtitle:
"",
team: "OBDH + PL",
category: "",
position: "Subsystem Managing Engineer",
image: eliot,
},

{
id: 8,
title: "Filip Kierzenka",
subtitle:
"Rising junior from Framingham, MA studying Applied Math and Computer Science. As part of the OBDH team, I am working to ensure that our computer systems survive the radiation of space. Outside of school work I like to play hockey, build things, and reinvent the wheel.",
category: "Onboard Data Handling Engineer",
position: "Engineer",
team: "OBDH + PL",
image: filip,
},
{
id: 55,
title: "Aaron Jeyaraj",
subtitle:
"",
team: "alumni",
category: "alumni",
position: "Engineer",
image: sbudnicNW,
},
{
id: 15,
title: "Hammad Izhar",
subtitle:
"",
team: "alumni",
category: "",
position: "Engineer",
image: sbudnicNW,
},
{
id: 56,
title: "Kazen Gallman",
subtitle:
"Class of '24, Studied Computer Science and Cognitive Neuroscience",
team: "OBDH + PL",
category: "",
position: "Engineer",
image: kazen,
},
{
id: 16,
title: "Benjamin Smith",
subtitle:
"",
team: "alumni",
category: "alumni",
position: "Engineer",
image: sbudnicNW,
},
{
id: 4,
title: "Haley Rose Flores",
subtitle:
"Haley Rose Flores is a class of '24 undergraduate student at Brown University studying Computer Science and Engineering. This is Haley’s first involvement in an engineering project at Brown University. During the summer before her senior year, Haley conducted research at the New Jersey Institute of Technology studying the process of self-assembly of multilayer graphene in water-containing impurities under the supervision of Dr. Dibakar Datta and Vidushi Sharma. As a part of the STEAM Academy throughout high school, Haley led the Green Technology House Project, which consisted of wiring a miniature house with solar panels, rechargeable batteries, and an Arduino. On the SBUDNIC team, Haley is a member of the Electrical Power System (EPS) subsystem and is responsible for designing and constructing the battery pack for the satellite alongside Brown alumnus, Shin-Ji Low.",
category: "Member of the EPS subsystem",
image: haley,
position: "Subsystem Managing Engineer",
team: "EPS",
},
{
id: 17,
title: "Shin-Ji Low",
subtitle:
"",
team: "EPS",
category: "",
position: "Engineer",
image: "https://media.licdn.com/dms/image/v2/C4E03AQH5hFJVQORkdg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1591261780188?e=1732752000&v=beta&t=6lDiUCwItwqOTM0nRu4LGAB2Bt5f7I1y5oC-Y0bwYew",
},
{
id: 24,
title: "Rick Fleeter",
subtitle:
"The resident space guy on the School of Engineering faculty since 2002. Brown AB 1976, PhD 1981 in engineering. Started building small satellites with Amsat while at Brown in the 1970s. During the 1980s and 1990s wrote several books and book chapters, taught professional courses and started a company all dedicated to making small satellites a reality. In addition to working at Brown I'm a visiting professor at La Sapienza in Rome, Italy where I live with my wife, Esther. I raced bicycles at Brown and still an avid rider and bike commuter in both countries.",
team: "Advisor",
category: "General",
position: "Faculty Advisor",
image: rick,
},
{
id: 66,
title: "Doug Stern",
subtitle:
"",
team: "Advisor",
category: "General",
position: "Industry Advisor for Structures",
image: sbudnicNW,
},
{
id: 25,
title: "Matteo Perotta",
subtitle:
"",
team: "Advisor",
category: "General",
position: "Industry Advisor for Systems Engineering",
image: sbudnicNW,
},
{
id: 26,
title: "Michael Umbritcht",
subtitle:
"",
team: "Advisor",
category: "General",
position: "Industry Advisor for Telemetry, Tracking, and Control",
image: sbudnicNW,
},
{
id: 27,
title: "Ray Z",
subtitle:
"",
team: "Advisor",
category: "General",
position: "Industry Advisor for Telemetry, Tracking, and Control",
image: sbudnicNW,
},
{
id: 45,
title: "Jennifer Wang",
subtitle:
"",
team: "Program Management and Public Relations",
category: "General",
position: "Program Analyst",
image: jenn,
},
{
id: 46,
title: "David Chen",
subtitle:
"",
team: "Program Management and Public Relations",
category: "General",
position: "Program Analyst",
image: "https://media.licdn.com/dms/image/D4E03AQE_VYkj0TNQeA/profile-displayphoto-shrink_200_200/0/1722967362793?e=2147483647&v=beta&t=DVTTVjicxgZApsxlmgtpSmUAGHF5APLpmOGcDm4mQfg",
},
{
id: 47,
title: "Christopher Pellinger",
subtitle:
"",
team: "Program Management and Public Relations",
category: "General",
position: "Program Analyst",
image: "https://media.licdn.com/dms/image/v2/C4E03AQG2XofFWkuuQQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1640452733951?e=2147483647&v=beta&t=_lsXRYhoj6ZIeh35HymE0RGJFabZkjZ3xnrUj1T5Bss",
},
{
id: 57,
title: "Dan Rapoport",
subtitle:
"Dan's background as an architect specializing in modular structures has prepared him to previsualize mechanical solutions and realize them using whatever tools necessary.",
team: "Research and Manufacturing",
category: "General",
position: "Research and Manufacturing Analyst",
image: rap,
},
{
id: 58,
title: "Mia Rollins",
subtitle:
"Mia Rollins is a video installation artist from Nashville, TN. They are in their last semester of their Sculpture MFA at the Rhode Island School of design. Their works examine the liminal space between the physical and virtual, science and magic, and memory and imagination.",
team: "Research and Manufacturing",
category: "General",
position: "Research and Manufacturing Analyst",
image: mia,
},
{
id: 29,
title: "Jared Johnson",
subtitle:
"",
team: "alumni",
category: "General",
position: "Program Manager Assistant",
image: sbudnicNW,
},
{
id: 30,
title: "Damir Kulzhanov",
subtitle:
"",
team: "alumni",
category: "General",
position: "Program Manager Assistant",
image: sbudnicNW,
},
{
id: 31,
title: "Raghav Puri",
subtitle:
"",
team: "alumni",
category: "General",
position: "Program Manager Assistant",
image: sbudnicNW,
},
{
id: 32,
title: "Vasudev Agarwal",
subtitle:
"",
team: "alumni",
category: "",
position: "Engineer",
image: sbudnicNW,
},
{
id: 33,
title: "Julien Cormary",
subtitle:
"",
team: "THERM",
category: "",
position: "Thermal Control System Engineer",
image: "https://media.licdn.com/dms/image/D4E03AQGDeTaUBDUXIA/profile-displayphoto-shrink_200_200/0/1718224727308?e=2147483647&v=beta&t=OM_6YuAzhZkKQnmorIhY6RlQzbkbahAN8UQQxaThUX0",
},
{
id: 36,
title: "Sejal Shah",
subtitle:
"",
team: "STR",
category: "",
position: "Engineer",
image: "https://media.licdn.com/dms/image/v2/C4D03AQFOY0t9xiFitg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1631312366460?e=1732752000&v=beta&t=_5PAOUDPkpZEO5ZGT9tDTRl5MQOZ3agggA6uQpgkHLM",
},
{
id: 34,
title: "Gabby Shieh",
subtitle:
"",
team: "STR",
category: "",
position: "Engineer",
image: gabby,
},
{
id: 35,
title: "Geoffrey Hazard",
subtitle:
"",
team: "alumni",
category: "",
position: "Engineer",
image: sbudnicNW,
},
{
id: 43,
title: "Ron Creel",
category: "Onboard Data Handling Engineer",
position: "Industry Advisor",
team: "alumni",
image: sbudnicNW,
},
{
id: 40,
title: "Brennan Vasquez",
category: "Onboard Data Handling Engineer",
position: "Engineer",
team: "alumni",
image: sbudnicNW,
},
{
id: 41,
title: "Timothy McDonough",
category: "Onboard Data Handling Engineer",
position: "Engineer",
team: "alumni",
image: sbudnicNW,
},
{
id: 42,
title: "Madeline Montagner",
category: "Onboard Data Handling Engineer",
position: "Engineer",
team: "alumni",
image: sbudnicNW,
},
{
id: 44,
title: "Daniel Wang",
category: "Onboard Data Handling Engineer",
position: "Engineer",
team: "alumni",
image: sbudnicNW,
},
{
id: 45,
title: "Lorenzo Bigagli",
subtitle:
"Since 2006 a researcher at the National Research Council of Italy, Institute of Atmospheric Pollution Research (CNR-IIA). MSc in Computer Science and Engineering in 1999. PhD in Methods and Technologies for Environmental Monitoring in 2008. My research focuses on Earth & Space Science Informatics, particularly addressing the transfer of technology between the scientific community and the society.",
category: "Advisor",
position: "CNR Advisor",
team: "Advisor",
image: lorenzo,
},
{
id: 88,
title: "Emanuele D'Andria IØELE",
subtitle: "Advisor who greatly facilitated the frequency clearance.",
team: "Advisor",
category: "General",
position: "AMSAT Italia Advisor",
image: sbudnicNW,
},
{
id: 89,
title: "Vikas Rana",
subtitle:
"",
category: "Engineer",
position: "Engineer",
team: "Testing",
image: "https://media.licdn.com/dms/image/D4E03AQH9KMfZr9CIbg/profile-displayphoto-shrink_200_200/0/1714050423254?e=2147483647&v=beta&t=8syk7jjEg4gSru1RIlqkMFVjKJJZ4hNudL7oUNfbPiU",
},
]

export { team }
