import {
  // sbudnicN,
  sbudnicNW,
  theo,
  rick,
  dheraj,
  ashton,
  daniel,
  haley,
  marco,
  filip,
  maddie,
  benji,
} from "../content/images"

const team = [
  {
    id: 1,
    title: "Rick Fleeter",
    subtitle:
      "The resident space guy on the School of Engineering faculty since 2002. Brown AB 1976, PhD 1981 in engineering. Started building small satellites with Amsat while at Brown in the 1970s. During the 1980s and 1990s wrote several books and book chapters, taught professional courses and started a company all dedicated to making small satellites a reality. In addition to working at Brown I'm a visiting professor at La Sapienza in Rome, Italy where I live with my wife, Esther. I raced bicycles at Brown and still an avid rider and bike commuter in both countries.",
    category: "Faculty Advisor",
    image: rick,
  },
  {
    id: 2,
    title: "Marco Cross",
    subtitle: "Hardware isn't hard. Perpetually inventing, designing, and making. I get antsy if my hands stop moving.",    category: "Subsystem Managing Engineer",
    image: marco,
    team: "AOCS",
    position: "Subsystem Managing Engineer"
  },
  {
    id: 52,
    title: "Marco Cross",
    subtitle: "Hardware isn't hard. Perpetually inventing, designing, and making. I get antsy if my hands stop moving.",
    category: "Chief Engineer",
    position: "Chief Engineer",
    image: marco,
    team: "Program Management and Public Relations",
  },
  {
    id: 42,
    title: "Marco Cross",
    subtitle: "Hardware isn't hard. Perpetually inventing, designing, and making. I get antsy if my hands stop moving.",
    category: "Lead Engineer",
    position: "Subsystem Managing Engineer",
    image: marco,
    team: "TCS",
  },
  {
    id: 3,
    title: "Dheraj Ganjikunta",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    category: "Program Manager",
    position: "Program Manager",
    image: dheraj,
    team: "Program Management and Public Relations",
  },
  
  {
    id: 5,
    title: "Benjamin Kilimnik",
    subtitle:
      "A junior at Brown University studying computer science with a focus on systems research, data science, and web design. When I'm not coding up a hot mess in the Computer Science department, you can find me working at the Center for Computation and Visualization, researching for Systems@Brown or reading historical fiction next to a radiator.",
    category: "Thermal Systems Engineer, Web Developer",
    image: benji,
  },
  {
    id: 6,
    title: "Ashton Lam",
    subtitle:"",
    category: "Marketing",
    position: "Marketing Manager",
    image: ashton,
    team: "Program Management and Public Relations",
  },
  {
    id: 21,
    title: "Elizabeth Kimmel",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Testing",
    category: "",
    position: "Subsystem Managing Engineer",
    image: sbudnicNW,
  },
  {
    id: 7,
    title: "Maddie Simons",
    subtitle:
      "I'm a member of the Brown class of '24 studying Biomedical Engineering! I'm super excited to be helping out with this project and have already learned so much.",
    category: "Testing Team Member",
    position: "Engineer",
    image: maddie,
    team: "Testing",
  },

  {
    id: 8,
    title: "Filip Kierzenka",
    subtitle:
      "Rising junior from Framingham, MA studying Applied Math and Computer Science. As part of the OBDH team, I am working to ensure that our computer systems survive the radiation of space. Outside of school work I like to play hockey, build things, and reinvent the wheel.",
    category: "Onboard Data Handling Engineer",
    team: "PL + OBDH",
    image: filip,
  },
  {
    id: 9,
    title: "Daniel Wang",
    subtitle:
      "Daniel is a rising senior MechE, fascinated by the neat applications of classical mechanics, who enjoys thinking about challenging energy distribution and efficiency problems. More broadly, Daniel wants to get more people thinking about civilization's major mass+energy flows, such as animal agriculture, and how they can be radically reimagined or replaced altogether.",
    category: "Thermal Engineer",
    image: daniel,
  },
  {
    id: 11,
    title: "Duncan Crane",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "TTC + GSEG",
    category: "Telemetry, Tracking, Control",
    position: "Subsystem Managing Engineer",
    image: sbudnicNW,
  },
  {
    id: 10,
    title: "Theo Fernandez",
    subtitle:
      "First year from Los Angeles, California who plans on concentrating Computer Science. I love computers, engineering, and space, as well as surfing, watching movies, biking, and tinkering.",
    team: "TTC + GSEG",
    category: "Telemetry, Tracking, Control",
    position: "Engineer",
    image: theo,
  },
  {
    id: 12,
    title: "Anthony Bishop-Gylys",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",    team: "TTC + GSEG",
    category: "Ground Segment",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 13,
    title: "Eliot Laidlaw",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",    team: "OBDH + PL",
    category: "",
    position: "Subsystem Managing Engineer",
    image: sbudnicNW,
  },
  {
    id: 55,
    title: "Aaron Jeyaraj",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",    team: "OBDH + PL",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 15,
    title: "Hammad Izhar",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",    team: "OBDH + PL",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 16,
    title: "Benjamin Smith",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",    team: "OBDH + PL",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 17,
    title: "Shin-Ji Low",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",    team: "EPS",
    category: "",
    position: "Subsystem Managing Engineer",
    image: sbudnicNW,
  },
  
  {
    id: 22,
    title: "Cameron Goodreau",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Testing",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 24,
    title: "Rick Fleeter",
    subtitle:
      "The resident space guy on the School of Engineering faculty since 2002. Brown AB 1976, PhD 1981 in engineering. Started building small satellites with Amsat while at Brown in the 1970s. During the 1980s and 1990s wrote several books and book chapters, taught professional courses and started a company all dedicated to making small satellites a reality. In addition to working at Brown I'm a visiting professor at La Sapienza in Rome, Italy where I live with my wife, Esther. I raced bicycles at Brown and still an avid rider and bike commuter in both countries.",
    team: "Advisor",
    category: "General",
    position: "Faculty Advisor",
    image: rick,
  },
  {
    id: 25,
    title: "Matteo Perotta",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Advisor",
    category: "General",
    position: "Industry Advisor for Systems Engineering",
    image: sbudnicNW,
  },
  {
    id: 26,
    title: "Michael Umbritcht",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Advisor",
    category: "General",
    position: "Industry Advisor for Telemetry, Tracking, and Control",
    image: sbudnicNW,
  },
  {
    id: 40,
    title: "Benjamin Kilimnik",
    subtitle:
      "A junior at Brown University studying computer science with a focus on systems research, data science, and web design. When I'm not coding up a hot mess in the Computer Science department, you can find me working at the Center for Computation and Visualization, researching for Systems@Brown or reading historical fiction next to a radiator.",
    team: "Program Management and Public Relations",
    category: "",
    position: "Web Developer & Designer",
    image: benji,
  },
  {
    id: 27,
    title: "Ray Z",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Advisor",
    category: "General",
    position: "Industry Advisor for Telemetry, Tracking, and Control",
    image: sbudnicNW,
  },
  {
    id: 28,
    title: "Selia Jindal",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Program Management and Public Relations",
    category: "General",
    position: "Program Manager Assistant",
    image: sbudnicNW,
  },
  {
    id: 29,
    title: "Jared Johnson",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Program Management and Public Relations",
    category: "General",
    position: "Program Manager Assistant",
    image: sbudnicNW,
  },
  {
    id: 30,
    title: "Damir Kulzhanov",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Program Management and Public Relations",
    category: "General",
    position: "Program Manager Assistant",
    image: sbudnicNW,
  },
  {
    id: 31,
    title: "Raghav Puri",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "Program Management and Public Relations",
    category: "General",
    position: "Program Manager Assistant",
    image: sbudnicNW,
  },
  {
    id: 39,
    title: "Benjamin Kilimnik",
    subtitle:
      "A junior at Brown University studying computer science with a focus on systems research, data science, and web design. When I'm not coding up a hot mess in the Computer Science department, you can find me working at the Center for Computation and Visualization, researching for Systems@Brown or reading historical fiction next to a radiator.",
    team: "TCS",
    category: "",
    position: "Engineer",
    image: benji,
  },
  {
    id: 32,
    title: "Vasudev Agarwal",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "TCS",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 33,
    title: "Sejal Shah",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "STR",
    category: "",
    position: "Subsystem Managing Engineer",
    image: sbudnicNW,
  },
  {
    id: 34,
    title: "Gabby Shieh",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "STR",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 35,
    title: "Geoffrey Hazard",
    subtitle: "Committed to building and launching a low-cost CubeSat into low earth orbit in record time.",
    team: "STR",
    category: "",
    position: "Engineer",
    image: sbudnicNW,
  },
  {
    id: 4,
    title: "Haley Rose Flores",
    subtitle:
      "Haley Rose Flores is a first-year undergraduate student at Brown University studying Computer Science and Engineering. This is Haley’s first involvement in an engineering project at Brown University. During the summer before her senior year, Haley conducted research at the New Jersey Institute of Technology studying the process of self-assembly of multilayer graphene in water-containing impurities under the supervision of Dr. Dibakar Datta and Vidushi Sharma. As a part of the STEAM Academy throughout high school, Haley led the Green Technology House Project, which consisted of wiring a miniature house with solar panels, rechargeable batteries, and an Arduino. On the SBUDNIC team, Haley is a member of the Electrical Power System (EPS) subsystem and is responsible for designing and constructing the battery pack for the satellite alongside Brown alumnus, Shin-Ji Low.",
    category: "Member of the EPS subsystem",
    image: haley,
    position: "Engineer",
    team: "EPS",
  },
]

export { team }
